### PR TITLE
Makes WpsServerImpl support parallel running processes + adds exception reports

### PR DESCRIPTION
**Pull request by pteigen**
Hey guys. 

This PR changes the behavior of the WpsServerImpl as it did not support parallel running processes. When passing an ExecutorService to WpsServerImpl that supports more than one thread one would expect the processes to run in parallel. Although they didn't because of workerFIFO and processRunning.

If one process at the time is what you want you should pass a "correct" implementation of ExecutorService

PS: I was concidering to make a property that could turn the old feature (with workerFIFO) on and off. But in the end I thought this was the better solution. I hope you agree :)

--
Petter

### CODE REVIEW

**Comment by SPalominos** [comment]
@pteigen  Thank you for the PR ! I'll take a look on it as soon as possible.

**Comment by pteigen** [comment]
Added a commit to this PR that adds some ExceptionReports (according to the standard) instead of crashing hard

**Comment by SPalominos** [comment]
@pteigen Thank you for your PR (and sorry for the long reacting time).
Before merging it, can you provide a contributor license agreement ?
You can send a mail to info@orbisgis.org instead of a comment (to avoid to have to do it on each contribution) with the the following statement:
`I wrote the code, it's mine, and I'm contributing to OrbisGIS for distribution licensed under the GPL 3.0.`

**Comment by pteigen** [comment]
I wrote the code, it's mine, and I'm contributing to OrbisGIS for distribution licensed under the GPL 3.0.

**Comment by SPalominos** [comment]
@pteigen Thank you !

**Pull request merged**
